import { asset } from "../lib/asset";

export const gameDevSnippets = [
  {
    id: 1,
    title: "Party Recruitment System",
    desc: "NPC joins the player's party, showing how character recruitment is handled in the 2.5D RPG prototype.",
    video: asset("media/snippet1.mp4"),
    thumb: asset("media/snippet1_thumb.png"),
    subsection: "Unity 2.5D Turn-Based RPG",
  },
  {
    id: 2,
    title: "Turn-Based Combat Victory",
    desc: "Demonstrates the combat loop, attack resolution, and victory sequence.",
    video: asset("media/snippet2.mp4"),
    thumb: asset("media/snippet2_thumb.png"),
    subsection: "Unity 2.5D Turn-Based RPG",
  },
  {
    id: 3,
    title: "Escape Mechanic",
    desc: "Showcases the flee option and the logic that lets the player retreat from battle when the odds turn against them.",
    video: asset("media/snippet3.mp4"),
    thumb: asset("media/snippet3_thumb.png"),
    subsection: "Unity 2.5D Turn-Based RPG",
  },
  {
    id: 4,
    title: "Defeat Sequence",
    desc: "Depicts the defeat condition and death animations for both characters.",
    video: asset("media/snippet4.mp4"),
    thumb: asset("media/snippet4_thumb.png"),
    subsection: "Unity 2.5D Turn-Based RPG",
  },
  {
    id: 5,
    title: "Laser Defender",
    desc: "A complete vertical shooter built in Unity using C# and 2D sprites.",
    video: asset("media/laser_defender.mp4"),
    thumb: asset("media/laser_defender_thumb.png"),
    subsection: "Complete C# Unity Game Developer 2D",
  },
  {
    id: 6,
    title: "TileVania",
    desc: "A fast-paced 2D platformer featuring animation, physics, and collectible mechanics.",
    video: asset("media/tilevania.mp4"),
    thumb: asset("media/tilevania_thumb.png"),
    subsection: "Complete C# Unity Game Developer 2D",
  },
  {
    id: 7,
    title: "Quiz Master",
    desc: "A multiple-choice trivia game that demonstrates UI, events, and score tracking in Unity.",
    video: asset("media/quiz_master.mp4"),
    thumb: asset("media/quiz_master_thumb.png"),
    subsection: "Complete C# Unity Game Developer 2D",
  },
  {
    id: 8,
    title: "Snowboarder",
    desc: "A side-scrolling physics game showcasing animation curves and motion control.",
    video: asset("media/snowboard.mp4"),
    thumb: asset("media/snowboard_thumb.png"),
    subsection: "Complete C# Unity Game Developer 2D",
  },
  {
    id: 9,
    title: "Kabadayı",
    desc: "A Class card that gives the user the heart of a lion.",
    image: asset("media/Kabadayı.png"),
    subsection: "Satirical Parody Card Game (85 Cards, 5 Versions)",
  },
  {
    id: 10,
    title: "Ajan",
    desc: "A Class card that makes the user be always one step ahead from his/her opponent.",
    image: asset("media/Ajan.png"),
    subsection: "Satirical Parody Card Game (85 Cards, 5 Versions)",
  },
  {
    id: 11,
    title: "Mafya",
    desc: "A Class card that lets the user make offers their opponents can't refuse.",
    image: asset("media/Mafya.png"),
    subsection: "Satirical Parody Card Game (85 Cards, 5 Versions)",
  },
  {
    id: 12,
    title: "Peruk",
    desc: "A humorous item card granting disguise and style bonuses.",
    image: asset("media/Peruk.png"),
    subsection: "Satirical Parody Card Game (85 Cards, 5 Versions)",
  },
];
