import { asset } from "../lib/asset";

export const webShowcase = [
  {
    id: 1,
    title: "Pokémon Browser Homepage",
    desc: "Main Pokémon list and type filtering interface — lists Pokémon from SQLite with generation and type filters.",
    image: asset("media/Pokeweb Homepage.png"),
    subsection: "PokéWeb (Django REST API)",
  },
  {
    id: 2,
    title: "PokéWeb API Links Page",
    desc: "Endpoints and HTML pages to query Pokémon by generation, type, or ID using Django REST Framework.",
    image: asset("media/Pokeweb Links.png"),
    subsection: "PokéWeb (Django REST API)",
  },
  {
    id: 3,
    title: "Database Schema Diagram",
    desc: "Entity-relationship diagram showing Pokémon, Type, and Generation enums in SQLite.",
    image: asset("media/Pokeweb.png"),
    subsection: "PokéWeb (Django REST API)",
  },
  {
    id: 4,
    title: "System Architecture Flowchart",
    desc: "Visual overview of PokéWeb's architecture — Client connects to Django REST API, which interacts with SQLite and PokéAPI.",
    image: asset("media/PokeWeb Flowchart.png"),
    subsection: "PokéWeb (Django REST API)",
  },
  {
    id: 5,
    title: "ElearnX Home Page",
    desc: "The main landing page of the ElearnX MOOC platform, featuring course search, live chat highlights, and learner testimonials.",
    image: asset("media/elearnx-homepage.png"),
    subsection: "ElearnX (Django REST + Channels + Redis)",
  },
  {
    id: 6,
    title: "ElearnX Courses Page",
    desc: "A responsive course browser where teachers publish lessons and students can enroll, view materials, and leave feedback.",
    image: asset("media/elearnx-courses.png"),
    subsection: "ElearnX (Django REST + Channels + Redis)",
  },
  {
    id: 7,
    title: "ElearnX Chat",
    desc: "A real-time WebSocket-based course chat built with Django Channels and Redis, enabling live discussions between teachers and students.",
    image: asset("media/elearnx-chat.png"),
    subsection: "ElearnX (Django REST + Channels + Redis)",
  },
  {
    id: 8,
    title: "ElearnX Database Design",
    desc: "Entity-relationship diagram showing normalized tables for users, courses, feedback, enrollments, materials, and notifications.",
    image: asset("media/elearnx-db-design.png"),
    subsection: "ElearnX (Django REST + Channels + Redis)",
  },
  {
    id: 9,
    title: "Normal Mountain Simulation (100 Creatures)",
    desc: "Final vertical positions on the normal slope, showing a greater spread and lower mean height due to increased difficulty.",
    image: asset("media/normal_mountain_part1.png"),
    subsection: "Genetic Algorithm Creature Simulation",
  },
  {
    id: 10,
    title: "Gentle Mountain Simulation",
    desc: "Final vertical positions of creatures on a gentle slope. Higher elevations indicate the ease of traversal on smoother terrain.",
    image: asset("media/gentle_mountain_part1.png"),
    subsection: "Genetic Algorithm Creature Simulation",
  },
  {
    id: 11,
    title: "Normal Mountain Simulation (200 Creatures)",
    desc: "Larger population test evaluating the effect of diversity and sample size on evolution and climbing performance.",
    image: asset("media/normal_mountain_part1_200_cr.png"),
    subsection: "Genetic Algorithm Creature Simulation",
  },
  {
    id: 12,
    title: "Evolutionary Fitness Comparison",
    desc: "Histogram comparison of fitness values before and after evolution (mutation rate = 1.0), showing slight improvement in mean fitness.",
    image: asset("media/normal_mountain_part2 mut_rate1.png"),
    subsection: "Genetic Algorithm Creature Simulation",
  },
  {
    id: 13,
    title: "Swagger Endpoints",
    desc: "Auth / Movie / Review APIs with CRUD, filtering, and watchlist management.",
    image: asset("media/movieforge-swagger.png"),
    subsection: "MovieForge (.NET Web API)",
  },
  {
    id: 14,
    title: "System Architecture Flowchart",
    desc: "Controllers (Auth, Movie, Review) → JWT / SMTP → Repository → EF Core → Database.",
    image: asset("media/movieforge-flowchart.png"),
    subsection: "MovieForge (.NET Web API)",
  },
  {
    id: 15,
    title: "Database Schema Diagram",
    desc: "Users, Movies, Reviews, and User_Watched_Movies tables linked via UUID keys (ERD).",
    image: asset("media/movieforge-erd.png"),
    subsection: "MovieForge (.NET Web API)",
  },
  {
    id: 16,
    title: "Day-Off Flow Diagram",
    desc: "End-to-end request → approval → scheduling workflow. (I did not design the visuals but implemented the system and contributed technical input to their design.)",
    image: asset("media/DayOffDiagram.png"),
    subsection: "PROJECT-HR (Multi-Tenant HR Platform - .NET 9 + ABP Framework)",
  },
  {
    id: 17,
    title: "Organization Units",
    desc: "Hierarchy and membership structure with parent-child units. (I did not design the visuals but implemented the system and contributed technical input to their design.)",
    image: asset("media/OrganizationUnits.png"),
    subsection: "PROJECT-HR (Multi-Tenant HR Platform - .NET 9 + ABP Framework)",
  },
  {
    id: 18,
    title: "User HR",
    desc: "Employee profile details, roles, and HR attributes. (I did not design the visuals but implemented the system and contributed technical input to their design.)",
    image: asset("media/UserHR.png"),
    subsection: "PROJECT-HR (Multi-Tenant HR Platform - .NET 9 + ABP Framework)",
  },
  {
    id: 19,
    title: "Work Calendar",
    desc: "Team-wide calendar showing work/leave schedules.",
    image: asset("media/WorkCalendar.png"),
    subsection: "PROJECT-HR (Multi-Tenant HR Platform - .NET 9 + ABP Framework)",
  },
];
